# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarIODeviceSettingSDK' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!


# Pods for Swift SDK
pod 'StarIO', '2.10.0'
pod 'StarIODeviceSetting', '1.0.1'

end
