# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift SDK' do
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!


# Pods for Swift SDK
pod 'StarIO', '2.9.1'
pod 'StarIO_Extension', '1.16.0'

end
